version: "2"

run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout

linters:
  enable:
    # Default enabled linters
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis (includes gosimple)
    - unused        # Check for unused constants, variables, functions and types

    # Additional useful linters
    - misspell      # Find commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter
    - gosec         # Security-focused linter
    - unconvert     # Remove unnecessary type conversions
    - goconst       # Find repeated strings that could be constants
    - gocyclo       # Computes cyclomatic complexities
    - prealloc      # Find slice declarations not pre-allocated

  settings:
    errcheck:
      # Check type assertions for errors
      check-type-assertions: true

    revive:
      # Enable only essential rules to avoid noise
      rules:
        - name: exported
        - name: package-comments
          disabled: true  # Disable package comment requirement for now
        - name: var-naming
        - name: indent-error-flow
        - name: if-return
        - name: superfluous-else
        - name: unused-parameter
          disabled: true  # Allow unused parameters in tests

    gosec:
      # Exclude certain security checks that are not relevant
      excludes:
        - G104  # Audit errors not checked (covered by errcheck)

    gocyclo:
      # Set reasonable complexity threshold
      min-complexity: 15

    goconst:
      # Minimum length of string constant
      min-len: 3
      # Minimum occurrences count to trigger
      min-occurrences: 3

  exclusions:
    # Exclude common false positives and test-specific issues
    rules:
      # Exclude gosec in test files where security is less critical
      - path: _test\.go
        linters:
          - gosec
          - goconst
          - gocyclo

      # Allow unused parameters in main function for CLI args
      - path: main\.go
        text: "parameter .* seems to be unused"
        linters:
          - revive

      # Exclude specific error strings from misspell in tests
      - path: _test\.go
        text: "misspell"
        linters:
          - misspell

formatters:
  enable:
    - gofmt         # Standard Go formatter
    - goimports     # Import management

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
